name: Bug report
description: >-
  If you experience a bug in Project64 and/or its maintained plugins, please open an
  issue here and fill out the template.
title: '[Bug]: '
labels:
  - bug
  - triage
assignees:
  - null
body:
  - type: markdown
    attributes: 
      value: '## FAQs and a warning'
  - type: markdown
    attributes: 
      value: >-

        Please read the support document in this repository before opening an issue!


        If you are having issues with a plugin that isn't included with or
        supported by the Project64 team, we cannot support you other then pointing
        you to the developer or repository for those plugins.


        Please join the Discord first and ask questions and ask for support there
        first. If the issue should require an open GitHub issue, somebody will ask
        you to open one. 
        
        We have a lot of people in the Discord who are more then
        happy to help you with any issues you may be having!


        Please avoid opening issues if you do not meet the minimum requirements
        for Project64. These are outlined in the README for this repository.
  - type: textarea
    id: what-should-happen
    attributes: 
      label: Expected behavior?
      description: How was the emulator supposed to behave
      placeholder: Tell us what you expect to see!; use screenshots if necessary.
      value: null
    validations: 
      required: true
  - type: textarea
    id: what-happened
    attributes: 
      label: Actual behavior?
      description: Describe in detail the issue you encountered.
      placeholder: Tell us what you see!; use screenshots if necessary.
      value: null
    validations: 
      required: true
  - type: textarea
    id: repro
    attributes: 
      label: Steps to reproduce the problem
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1.
        2.
        3.
        4.
        5.
        ...
    validations: 
      required: true
  - type: textarea
    id: error-messages
    attributes: 
      label: Error messages?
      description: Was there an error message?
      placeholder: List any error messages here!; use screenshots if necessary.
      value: null
    validations: 
      required: false
  - type: textarea
    id: ROM_details
    attributes: 
      label: What game were you playing?
      description: What is the specific game/ROM that you encountered an issue with?
      value: |
        Title:

        Nintendo 64 game or Nintendo 64 Disk Drive:

        ROM information (First you must uncheck "hide advanced settings" in the settings menu, then File > ROM info should show up, post the information contained there in this field. Alternatively, you can right click the ROM in the ROM browser and hit "ROM information".): 
        Save type: (attach game save or save state here)

        Original or modified ROM?:(attach patch if applicable here)
    validations: 
      required: false
  - type: textarea
    id: SysInfo
    attributes: 
      label: Specifications and build details
      description: >-
        List your PC specifications/information, you can obtain this from MSINFO32 and the
        emulators title bar and about page.
      value: |
        Project64: (include commit version number and whether you are using the
        32-bit or 64-bit version)

        OS: (include version and OS build number using WinVer):

        CPU:

        RAM:

        Graphics:
    validations: 
      required: true
  - type: checkboxes
    id: DefaultPlugins
    attributes: 
      label: Using included plugins
      description: >-
        Please make sure you are using the included plugins before opening an
        issue:
      options:
        - label: >-
            I can confirm I am using the included RSP, audio, input, and graphics
            plugins
          required: true
  - type: textarea
    id: PluginsUsed
    attributes: 
      label: Plugins used while the issue occurred
      description: What plugins are the issues occuring with?
      value: |
        Graphics plugin (and HLE or LLE):
        Audio plugin:
        Input plugin:
        RSP plugin:
    validations: 
      required: true
  - type: textarea
    id: RecompilerorInterpreter
    attributes: 
      label: Does the issue manifest with the Interpreter core?
      description: You can change this setting in the Rom Configuration (Requires "hide advanced settings" unchechecked)
      value: |
        You can also specify here if certain Recompiler setting combinations allows the game to boot.
    validations: 
      required: true      
  - type: checkboxes
    id: Copyright_Compliance
    attributes: 
      label: Copyright Compliance
      description: >-
        Please do not attach any files that infringe on the copyright of any
        party.
      options:
        - label: There are no infringing files attached to this bug report.
          required: true
  - type: checkboxes
    id: Latest_Nightly
    attributes: 
      label: Using Latest Nightly
      description: >-
        Are you using the [latest nightly build](https://www.pj64-emu.com/nightly-builds)?
      options:
        - label: I am using the latest nightly build.
          required: true
