//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NRagePluginV2.rc
//
#define IDC_STATIC						-1
#define IDC_STOREINDB                   3
#define IDC_ERASEFROMDB                 4
#define IDC_SAVEPROFILE                 5
#define IDC_UPDATEDB                    6
#define IDC_SAVEBINARY                  6
#define IDC_LOADPROFILE                 7
#define IDC_LOADSHORTCUTS               7
#define IDUSE                           8
#define IDD_MAINCFGDIALOG               101
#define IDD_CONTROLLER                  104
#define IDD_SHORTCUT                    106
#define IDD_CONTROLS                    108
#define IDD_CONTROLLERPAK               109
#define IDD_MODIFIER                    111
#define IDD_PAK_MEMPAK                  112
#define IDD_PAK_TRANSFER                113
#define IDD_PAK_ADAPTOID                115
#define IDD_DEVICES                     117
#define IDD_PAK_TEXT                    118
#define IDD_MOD_MOVE                    119
#define IDD_FOLDERS                     120
#define IDD_MOD_MACRO                   121
#define IDD_MOD_CONFIG                  122
#define IDD_PAK_RUMBLE                  123
#define IDR_PROFILE_DEFAULT1            139
#define IDS_ERR_DINOTFOUND              141
#define IDS_ERR_DICREATE                142
#define IDS_DLG_MPCHOOSE                143
#define IDS_ERR_MPREAD                  144
#define IDR_SHORTCUT1                   144
#define IDR_SHORTCUTS_DEFAULT           144
#define IDS_ERR_GBROM                   145
#define IDD_XCONTROLS                   145
#define IDS_ERR_GBSRAMERR               146
#define IDS_VERSTRING                   147
#define IDS_TAB_CONTROLLER              148
#define IDS_TAB_SHORTCUTS               149
#define IDS_TAB_CONTROLS                150
#define IDS_TAB_DEVICES                 151
#define IDS_TAB_MODIFIERS               152
#define IDS_TAB_CONTROLLERPAK           153
#define IDS_DLG_CLEAR                   154
#define IDS_DLG_CLEAR_TITLE             155
#define IDS_DLG_CONTROLRESTORE          156
#define IDS_DLG_CONTROLRESTORE_TITLE    157
#define IDS_ERR_PROFWRITE               158
#define IDS_ERR_PROFREAD                159
#define IDS_C_POLLING                   160
#define IDS_C_RANGE                     161
#define IDS_D_MSX                       162
#define IDS_D_MSY                       163
#define IDS_D_DEADZONE                  164
#define IDS_D_RUMBLESTR                 165
#define IDS_M_MOVEVALUE                 166
#define IDS_M_TAB_NONE                  167
#define IDS_M_TAB_MOVE                  168
#define IDS_M_TAB_MACRO                 169
#define IDS_M_TAB_CONFIG                170
#define IDS_M_MOUSE_PREFIX              171
#define IDS_M_KB_PREFIX                 172
#define IDS_M_NONE                      173
#define IDS_M_MOVE                      174
#define IDS_M_MACRO                     175
#define IDS_M_CONFIG                    176
#define IDS_M_ASSIGNED                  177
#define IDS_M_TYPE                      178
#define IDS_M_PARAM                     179
#define IDS_P_NONE                      180
#define IDS_P_MEMPAK                    181
#define IDS_P_RUMBLEPAK                 182
#define IDS_P_TRANSFERPAK               183
#define IDS_P_VOICEPAK                  184
#define IDS_P_ADAPTOIDPAK               185
#define IDS_P_MEM_NORAW                 186
#define IDS_P_RUMBLE_NORAW              187
#define IDS_P_RUMBLE_RAW                188
#define IDS_P_TRANSFER_NORAW            189
#define IDS_P_VOICE_RAW                 190
#define IDS_P_ADAPTOID_NORAW            191
#define IDS_P_NONE_RAWNORAW             192
#define IDS_P_MEM_NOCHANGE              193
#define IDS_P_MEM_NAME                  194
#define IDS_P_MEM_REGION                195
#define IDS_P_MEM_BLOCKS                196
#define IDS_DLG_DELETEPAK               197
#define IDS_DLG_FORMATPAK               198
#define IDS_DLG_DELETENOTE              199
#define IDS_P_MEM_BLOCKSFREE            200
#define IDS_P_MEM_INUSE                 201
#define IDS_P_MEM_WRONGSIZE             202
#define IDS_P_MEM_NONESELECTED          203
#define IDS_P_MEM_DAMAGED               204
#define IDS_BUTTON_UNASSIGNED           205
#define IDS_STRING206                   206
#define IDS_ERR_SHORTREAD               206
#define IDS_DLG_SHORTCUTRESTORE         207
#define IDS_DLG_SHORTCUTRESTORE_TITLE   208
#define IDS_C_GAMEPAD                   209
#define IDS_C_KEYBOARD                  210
#define IDS_C_MOUSE                     211
#define IDS_C_XAXIS                     212
#define IDS_C_YAXIS                     213
#define IDS_C_ZAXIS                     214
#define IDS_C_XROT                      215
#define IDS_C_YROT                      216
#define IDS_C_ZROT                      217
#define IDS_C_SLIDER                    218
#define IDS_C_POV                       219
#define IDS_C_BUTTON                    220
#define IDS_C_WHEEL                     221
#define IDS_C_UNKNOWN                   222
#define IDS_DLG_ABOUT                   223
#define IDS_DLG_ABOUT_TITLE             224
#define IDS_ERR_NOINIT                  225
#define IDS_POP_MOUSEUNLOCKED           226
#define IDS_POP_MOUSELOCKED             227
#define IDS_POP_CHANGEPAK               228
#define IDS_ERR_MAPVIEW                 229
#define IDS_DLG_CPF                     230
#define IDS_DLG_MPKN64                  231
#define IDS_DLG_A64                     232
#define IDS_DLG_GBGBC                   233
#define IDS_DLG_SVSAV                   234
#define IDS_ERR_HANDLER                 235
#define IDS_ERR_MEM_NOSPEC              236
#define IDS_DLG_MEM_READONLY            237
#define IDS_ERR_MEMOPEN                 238
#define IDS_DLG_MEM_BADADDRESSCRC       239
#define IDS_P_MEM_NOREGION              240
#define IDS_P_MEM_BETA                  241
#define IDS_P_MEM_NTSC                  242
#define IDS_P_MEM_GERMANY               243
#define IDS_P_MEM_USA                   244
#define IDS_P_MEM_FRANCE                245
#define IDS_P_MEM_ITALY                 246
#define IDS_P_MEM_JAPAN                 247
#define IDS_P_MEM_EUROPE                248
#define IDS_P_MEM_SPAIN                 249
#define IDS_P_MEM_AUSTRALIA             250
#define IDS_P_MEM_PAL                   251
#define IDS_P_MEM_UNKNOWNREGION         252
#define IDS_ERR_NOTEWRITE               253
#define IDS_ERR_MEMPAK_SPACE            254
#define IDS_ERR_MEMPAK_NONOTES          255
#define IDS_ERR_NOTEEOF                 256
#define IDS_ERR_NOTEREAD                257
#define IDS_ERR_TITLE                   258
#define IDS_DLG_MSG_TITLE               259
#define IDS_DLG_WARN_TITLE              260
#define IDS_PLUGIN_TITLE                261
#define IDS_ERR_MPCREATE                262
#define IDS_DLG_SC                      263
#define IDS_P_MEM_ERROR                 264
#define IDS_P_R_NODEVICE                265
#define IDS_STRING266                   266
#define IDS_P_TRANS_NOCHANGE            266
#define IDS_STRING267                   267
#define IDS_DLG_TPAK_READONLY           267
#define IDS_STRING268                   268
#define IDS_P_SWITCHING                 268
#define IDC_ROMDESC                     1003
#define IDC_ROMCONFIG                   1004
#define IDC_AUTOCONFIG                  1005
#define IDC_CONTROLLERTAB               1006
#define IDC_DDOWN                       1006
#define IDC_CURRENTCONFIG               1007
#define IDC_DLEFT                       1007
#define IDC_ROMID                       1008
#define IDC_DRIGHT                      1008
#define IDC_DUP                         1009
#define IDC_ADOWN                       1010
#define IDC_ALEFT                       1011
#define IDC_ARIGHT                      1012
#define IDC_UPPERTAB                    1013
#define IDC_AUP                         1013
#define IDC_CDOWN                       1014
#define IDC_CLEFT                       1015
#define IDC_CRIGHT                      1016
#define IDC_PAKTYPE                     1017
#define IDC_CUP                         1017
#define IDC_RIGHTTRIGGER                1018
#define IDC_LEFTTRIGGER                 1019
#define IDC_PAKAREA                     1020
#define IDC_SBUTTON                     1020
#define IDC_ABUTTON                     1021
#define IDC_BBUTTON                     1022
#define IDC_ZTRIGGER                    1023
#define IDC_MEMPAKLIST                  1025
#define IDC_BROWSE                      1026
#define IDC_APPCHANGES                  1026
#define IDC_MEMPAK_BROWSE_ABS           1027
#define IDC_RESET                       1027
#define IDC_GBSAVE_BROWSE               1027
#define IDC_GBROM_BROWSE_REL            1028
#define IDC_MEMPAKBROWSER               1029
#define IDC_GBROM_BROWSE_ABS            1029
#define IDC_GBSAVE_BROWSE_ABS           1030
#define IDC_GBSAVE_BROWSE_REL           1031
#define IDC_CTRDEVICE                   1032
#define IDC_DEADZONE                    1033
#define IDC_RUMBLE1                     1034
#define IDC_YMODIFIER                   1034
#define IDC_RUMBLE2                     1035
#define IDC_RUMBLE3                     1036
#define IDC_RUMBLESTRENGTH              1037
#define IDC_MSSENSITIVITY_X             1038
#define IDC_N64RANGE                    1039
#define IDC_MSSENSITIVITY_Y             1039
#define IDC_PLUGGED                     1040
#define IDC_CTRRANGE                    1041
#define IDC_RAWMODE                     1042
#define IDT_MSSENSITIVITY_X             1043
#define IDT_DEADZONE                    1044
#define IDT_RUMBLESTRENGTH              1045
#define IDT_MSSENSITIVITY_Y             1046
#define IDT_MEMPAKSTATE                 1048
#define IDT_RANGE                       1049
#define IDC_CLEARCONTROLLER             1050
#define IDC_MODIFIERLIST                1054
#define IDC_PROPWINDOW                  1055
#define IDC_KILLMODIFIER                1056
#define IDC_NEWMODIFIER                 1057
#define IDC_XMODIFIER                   1059
#define IDT_XMODIFIER                   1060
#define IDT_YMODIFIER                   1061
#define IDC_ASSIGNMOD                   1063
#define IDT_ASSIGNMOD                   1064
#define IDC_MODTYP                      1065
#define IDC_MEMPAK_REL                  1067
#define IDC_MEMPAK_ABS                  1068
#define IDC_MEMPAK_REL_EDIT             1069
#define IDC_MEMPAK_ABS_EDIT             1070
#define IDC_GBROM_REL                   1071
#define IDC_GBROM_ABS                   1072
#define IDC_GBROM_REL_EDIT              1073
#define IDC_GBROM_ABS_EDIT              1074
#define IDC_GBSAVE_REL                  1075
#define IDC_GBSAVE_ABS                  1076
#define IDC_GBSAVE_REL_EDIT             1077
#define IDC_GBSAVE_ABS_EDIT             1078
#define IDC_GBSAVE_SAME                 1079
#define IDC_MEMPAK_BROWSE_REL           1081
#define IDC_CHGDIR                      1082
#define IDT_PAKDESC                     1084
#define IDC_TOGGLE                      1085
#define IDC_XNEGATE                     1086
#define IDC_YNEGATE                     1087
#define IDC_ZTRIG                       1090
#define IDC_RAPIDFIREMODE               1091
#define IDC_LTRIG                       1092
#define IDC_RTRIG                       1093
#define IDC_SETNOPAK_P1                 1096
#define IDC_LOCKMOUSE                   1097
#define IDT_LEFTTRIGGER                 1100
#define IDT_MODTYP                      1100
#define IDT_RIGHTTRIGGER                1101
#define IDT_ABUTTON                     1102
#define IDC_SETMEMPAK_P1                1102
#define IDC_ACCELERATEX                 1102
#define IDT_BBUTTON                     1103
#define IDC_ACCELERATEY                 1103
#define IDT_CDOWN                       1104
#define IDC_SETRUMBLEPAK_P1             1104
#define IDT_CRIGHT                      1105
#define IDT_CLEFT                       1106
#define IDC_SETTRANSFERPAK_P1           1106
#define IDT_CUP                         1107
#define IDT_DUP                         1108
#define IDC_SETADAPTOIDPAK_P1           1108
#define IDT_DLEFT                       1109
#define IDT_DRIGHT                      1110
#define IDC_SWMEMRUMBLE_P1              1110
#define IDT_DDOWN                       1111
#define IDT_SBUTTON                     1112
#define IDC_SWMEMADAPTOID_P1            1112
#define IDT_ZTRIGGER                    1113
#define IDT_ADOWN                       1114
#define IDC_SETNOPAK_P2                 1114
#define IDT_ALEFT                       1115
#define IDT_ARIGHT                      1116
#define IDC_SETMEMPAK_P2                1116
#define IDT_AUP                         1117
#define IDC_SETRUMBLEPAK_P2             1118
#define IDC_CONFIG1                     1119
#define IDC_SETTRANSFERPAK_P2           1120
#define IDC_CONFIG2                     1120
#define IDC_CONFIG3                     1121
#define IDC_SETADAPTOIDPAK_P2           1122
#define IDC_CONFIGCYCLE                 1122
#define IDC_SWMEMRUMBLE_P2              1124
#define IDC_MOUSEX                      1124
#define IDC_MOUSEY                      1125
#define IDC_SWMEMADAPTOID_P2            1126
#define IDC_KEYX                        1126
#define IDC_KEYY                        1127
#define IDC_DELMEMPAK                   1127
#define IDC_SETNOPAK_P3                 1128
#define IDC_FORMATMEMPAK                1128
#define IDC_SAVENOTE                    1129
#define IDC_VISUALRUMBLE                1129
#define IDC_SETMEMPAK_P3                1130
#define IDC_INSERTNOTE                  1130
#define IDC_STATE                       1130
#define IDC_DELETENOTE                  1131
#define IDC_SETRUMBLEPAK_P3             1132
#define IDSAVE                          1132
#define IDC_GBSAVEPANEL                 1133
#define IDC_SETTRANSFERPAK_P3           1134
#define IDC_MEMPAKPANEL                 1134
#define IDC_GBROMPANEL                  1135
#define IDC_SETADAPTOIDPAK_P3           1136
#define IDC_SETDEFAULT                  1136
#define IDC_SWMEMRUMBLE_P3              1138
#define IDC_GBROM_EDIT                  1138
#define IDC_SWMEMADAPTOID_P3            1140
#define IDC_GBROM_BROWSE                1140
#define IDC_GBSAVE_EDIT                 1141
#define IDC_SETNOPAK_P4                 1142
#define IDC_VERSIONSTRING               1142
#define IDC_RAPIDFIREENABLE             1143
#define IDC_SETMEMPAK_P4                1144
#define IDC_RAPIDFIRERATE               1145
#define IDC_SETRUMBLEPAK_P4             1146
#define IDC_RAPIDFIREMODERATE           1146
#define IDC_SETTRANSFERPAK_P4           1148
#define IDC_DEADPANMOUSEY               1148
#define IDC_BUFFEREDMOUSEY              1149
#define IDC_SETADAPTOIDPAK_P4           1150
#define IDC_ABSOLUTEMOUSEY              1150
#define IDC_DEADPANMOUSEX               1151
#define IDC_SWMEMRUMBLE_P4              1152
#define IDC_BUFFEREDMOUSEX              1152
#define IDC_ABSOLUTEMOUSEX              1153
#define IDC_SWMEMADAPTOID_P4            1154
#define IDC_RUMBLETEST                  1154
#define IDC_SETDEFAULTSC                1156
#define IDC_SAVESHORTCUTS               1157
#define IDC_COMBO1                      1158
#define IDC_LANGUAGE                    1160
#define IDC_SHOWMESSAGES                1162
#define IDC_XC_USE                      1178
#define IDC_XINPUT_ENABLER              1179
#define IDC_XINPUT_TITLE                1180
#define IDC_XC_A                        1181
#define IDC_XC_B                        1182
#define IDC_XC_X                        1183
#define IDC_XC_Y                        1184
#define IDC_XC_LB                       1185
#define IDC_XC_RB                       1186
#define IDC_XC_LTSB                     1187
#define IDC_XC_RTSB                     1188
#define IDC_XC_LT                       1189
#define IDC_XC_RT                       1190
#define IDC_XC_BACK                     1191
#define IDC_XC_START                    1192
#define IDC_XC_DPAD                     1193
#define IDC_XC_LTS                      1194
#define IDC_XC_RTS                      1195
#define IDC_N64MOUSE                    1196
#define IDC_BACKGROUNDINPUT             1197

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1198
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
