//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UI Resources.rc
//
#define IDAPPLY                         3
#define IDI_PJ64_Icon                   101
#define IDD_Rom_Information             104
#define IDD_Key_Prompt                  108
#define IDI_RIGHT                       110
#define IDI_LEFT                        111
#define IDB_TRI_STATE                   113
#define IDD_Cheats_DumpMemory           117
#define IDD_Debugger_Memory             118
#define IDD_Debugger_Search             120
#define IDD_Settings_PlugSel            121
#define IDR_MEM_SEARCH                  121
#define IDD_Debugger_TLB                123
#define IDB_LISTITEMS                   123
#define IDC_DIVIDER                     124
#define IDD_Logging_Registers           125
#define IDC_HYPERLINK                   125
#define IDD_Logging_PifRam              126
#define IDD_Logging_General             127
#define IDD_About                       128
#define IDD_Settings_Directory          131
#define IDD_Settings_Advanced           132
#define IDD_Settings_GameGeneral        133
#define IDD_Cheats_Select               134
#define IDD_Cheats_List                 135
#define IDD_Cheats_CodeEx               136
#define IDD_Cheats_Range                137
#define IDD_Cheats_Add                  138
#define IDD_Settings_ShellInt           139
#define IDD_Settings_RomBrowser         140
#define IDD_About_UserInfo              141
#define IDD_About_Ini                   143
#define IDB_ABOUT_LOGO                  143
#define IDD_Settings_General            144
#define IDD_Settings_Accelerator        145
#define IDD_Settings_Config             149
#define IDD_Support_Project64           150
#define IDD_Support_EnterCode           151
#define IDR_POPUP                       155
#define IDR_CHEAT_MENU                  160
#define IDD_Lang_Select                 161
#define IDD_Settings_GameRecompiler     162
#define IDD_Settings_GamePlugin         163
#define IDD_Settings_GameStatus         164
#define IDC_MENU_ITEM_TEXT              1000
#define IDC_CLOSE_BUTTON                1001
#define IDC_LIST2                       1003
#define IDC_CURRENT_KEYS                1003
#define RSP_LIST                        1004
#define RSP_ABOUT                       1006
#define IDC_ASSIGN                      1006
#define IDC_BTN_CHOOSE_FILE             1006
#define IDC_DUMP_MEM                    1006
#define IDC_INFO_FILENAME               1007
#define IDC_BTN_RDRAM                   1007
#define IDC_REFRSH_MEM                  1007
#define IDC_INFO_ROMNAME                1008
#define IDC_BUTTON3                     1008
#define IDC_RESET_PAGE                  1008
#define IDC_INFO_CARTID                 1009
#define IDC_VIRTUALKEY                  1009
#define IDC_VALUE_ALIGN                 1009
#define IDC_FRAME_DISPLAY_TYPE          1009
#define IDC_RESET_ALL                   1009
#define IDC_INFO_ROMSIZE                1010
#define IDC_KEY_PROMPT                  1010
#define IDC_BTN_SPMEM                   1010
#define IDC_INFO_CIC                    1011
#define IDC_CTL                         1011
#define IDC_CACHE                       1011
#define IDC_ROM_FIXEDAUDIO              1011
#define IDC_DEBUGGER                    1011
#define IDC_USE_ALT_PC                  1011
#define IDC_HLE_GFX                     1011
#define IDC_CHK_VADDR                   1011
#define IDC_SEARCH_HEX                  1011
#define IDC_DISPLAY_FRAMERATE           1012
#define IDC_INFO_MANUFACTURER           1012
#define IDC_ALT                         1012
#define IDC_LIST                        1012
#define IDC_HLE_AUDIO                   1012
#define IDC_SMM_CACHE                   1012
#define IDC_CASE_SENSITIVE              1012
#define IDC_ROM_32BIT                   1012
#define IDC_INFO_COUNTRY                1013
#define IDC_SHIFT                       1013
#define IDC_TLB                         1013
#define IDC_TLB_ENTRIES                 1013
#define IDC_SMM_DMA                     1013
#define IDC_UNKNOWN_ALIGN               1013
#define IDC_DELAY_DP                    1013
#define IDC_INFO_CRC1                   1014
#define IDC_ASSIGNED_MENU_ITEM          1014
#define IDC_TLB_RULES                   1014
#define IDC_INFO_CRC2                   1015
#define IDC_GOOD_NAME                   1015
#define GFX_LIST                        1016
#define IDC_INFO_MD5                    1016
#define IDC_STATUS_TEXT                 1016
#define IDC_STATUS_TYPE                 1017
#define IDC_NOTES_CORE                  1018
#define GFX_ABOUT                       1019
#define IDC_NOTES_PLUGIN                1019
#define IDC_NOTES_CORE_TEXT             1020
#define IDC_NOTES_PLUGIN_TEXT           1021
#define IDC_NAME                        1022
#define IDC_CODE                        1023
#define IDC_CHEATNOTES                  1024
#define IDC_ADDR_EDIT                   1024
#define IDC_CODE_DES                    1025
#define IDC_E_START_ADDR                1027
#define AUDIO_LIST                      1028
#define IDC_E_END_ADDR                  1028
#define IDC_E_ALT_PC                    1029
#define IDC_FILENAME                    1030
#define AUDIO_ABOUT                     1031
#define IDC_FORMAT                      1031
#define CONT_LIST                       1032
#define CONT_ABOUT                      1035
#define IDC_SCRL_BAR                    1035
#define IDC_CP0_WRITE                   1036
#define IDC_C_CPU_STATE                 1036
#define IDC_CP0_READ                    1037
#define IDC_S_CPU_STATE                 1037
#define IDC_S_CURRENT_KEYS              1038
#define IDC_EXCEPTIONS                  1039
#define IDC_S_SELECT_SHORT              1039
#define IDC_INTERRUPTS                  1040
#define IDC_S_CURRENT_ASSIGN            1040
#define IDC_SMM_VALIDATE                1041
#define IDC_ROM_HEADER                  1042
#define IDC_SMM_PROTECT                 1042
#define IDC_UNKOWN                      1043
#define IDC_FUNCFIND                    1043
#define IDC_RI_REG                      1044
#define IDC_SMM_TLB                     1044
#define IDC_SI_REG                      1045
#define IDC_SMM_STORE                   1045
#define IDC_RDRAM                       1046
#define IDC_SMM_FRAME                   1046
#define IDC_SP_REG                      1047
#define IDC_PADDR_START                 1047
#define IDC_DPC_REG                     1048
#define IDC_ADDR_END                    1048
#define IDC_DPS_REG                     1049
#define IDC_RADIO_VALUE                 1049
#define IDC_MI_REG                      1050
#define IDC_RADIO_TEXT                  1050
#define IDC_VI_REG                      1051
#define IDC_RADIO_JAL                   1051
#define IDC_AI_REG                      1052
#define IDC_SEARCH_VALUE                1052
#define IDC_PI_REG                      1053
#define IDC_SEARCH_TEXT                 1053
#define IDC_SI_DMA                      1054
#define IDC_JAL_ADDR                    1054
#define IDC_DIRECT_WRITE                1055
#define IDC_BTN_SEARCH                  1055
#define IDC_DMA_WRITE                   1056
#define IDC_RESET_BUTTON                1056
#define IDC_DIRECT_READ                 1057
#define IDC_MAX_SEARCH                  1057
#define IDC_DMA_READ                    1058
#define IDC_CONT_PAK                    1059
#define IDC_SEARCH_MEM                  1059
#define IDC_BTN_ROM                     1061
#define IDC_TEXTURE_OTHER               1062
#define IDC_RADIO_UNKNOWN               1062
#define IDC_TEXTURE_DIR                 1063
#define IDC_CMB_UNKNOWN                 1063
#define IDC_TEXTURE_DEFAULT             1064
#define IDC_LST_RESULTS                 1064
#define IDC_SELECT_TEXTURE_DIR          1065
#define IDC_MEM_DETAILS                 1065
#define IDC_PLUGIN_OTHER                1066
#define IDC_BORDER_RESULTS              1066
#define IDC_PLUGIN_DIR                  1067
#define IDC_PLUGIN_DEFAULT              1068
#define IDC_SELECT_PLUGIN_DIR           1069
#define IDC_UP                          1069
#define IDC_AUTO_OTHER                  1070
#define IDC_DOWN                        1070
#define IDC_TEAM                        1070
#define IDC_AUTO_DIR                    1071
#define IDC_ZILMAR_DETAILS              1071
#define IDC_AUTO_DEFAULT                1072
#define IDC_JABO_DETAILS                1072
#define IDC_SELECT_AUTO_DIR             1073
#define IDC_SMIFF_DETAILS               1073
#define IDC_INSTANT_OTHER               1074
#define IDC_GENT_DETAILS                1074
#define IDC_INSTANT_DIR                 1075
#define IDC_ZILMAR                      1075
#define IDC_INSTANT_DEFAULT             1076
#define IDC_JABO                        1076
#define IDC_SELECT_INSTANT_DIR          1077
#define IDC_SMIFF                       1077
#define IDC_SNAP_OTHER                  1078
#define IDC_GENT                        1078
#define IDC_SNAP_DIR                    1079
#define IDC_THANKS                      1079
#define IDC_SNAP_DEFAULT                1080
#define IDC_THANK_LIST                  1080
#define IDC_SELECT_SNAP_DIR             1081
#define IDC_INFO1                       1081
#define IDC_INFO2                       1082
#define IDC_INFO3                       1083
#define IDC_START_ON_ROM_OPEN           1084
#define IDC_LABEL1                      1084
#define IDC_BLOCK_LINKING               1085
#define IDC_LABEL2                      1085
#define IDC_LABEL3                      1086
#define IDC_RDRAM_SIZE                  1087
#define IDC_VERSION                     1087
#define IDC_CPU_TYPE                    1088
#define IDC_SELECT_LANG                 1088
#define IDC_SAVE_TYPE                   1089
#define IDC_MENU_ITEMS                  1089
#define IDC_PAGELIST                    1090
#define IDC_CPU_TYPE_TEXT               1092
#define IDC_ZIP                         1092
#define IDC_SETTING_INFO                1092
#define IDC_GOOD_NAME_TEXT              1093
#define IDC_FUNCFIND_TEXT               1094
#define IDC_REMEMBER                    1095
#define IDC_GFX_NAME                    1095
#define IDC_AUTOSLEEP                   1096
#define IDC_COUNTFACT_TEXT              1096
#define IDC_RSP_NAME                    1097
#define IDC_REMEMBERDIR                 1097
#define IDC_VIREFESH_TEXT               1097
#define IDC_VIREFRESH                   1098
#define IDC_AUDIO_NAME                  1099
#define IDC_ROM_REGCACHE                1099
#define IDC_COUNTPERBYTE_TEXT           1099
#define IDC_BORDER                      1099
#define IDC_CONT_NAME                   1100
#define IDC_COUNTPERBYTE                1100
#define ID_SUPPORT_PJ64                 1100
#define IDC_DIR_FRAME1                  1101
#define IDC_ROM_FASTSP                  1101
#define IDC_INFO                        1101
#define IDC_AUDIO_SIGNAL                1102
#define IDC_DIR_TEXTURE_FRAME           1102
#define IDC_ENTER_CODE                  1102
#define IDC_DESCRIPTION                 1102
#define IDC_DIR_FRAME3                  1103
#define IDC_DIR_FRAME4                  1104
#define IDC_DIR_FRAME5                  1105
#define IDC_MAXROMS_TXT                 1111
#define IDC_ROMSEL_TEXT2                1112
#define IDC_MAXROMDIR_TXT               1113
#define IDC_ROMSEL_TEXT4                1114
#define IDC_UNMARK                      1119
#define IDC_NOTES                       1120
#define IDC_CHEAT_LIST                  1121
#define IDC_CHEAT_NAME                  1122
#define IDC_DELAY_SI                    1123
#define IDC_VALUE                       1124
#define IDC_RANGE                       1125
#define IDC_ADD                         1126
#define IDC_CODE_NAME                   1130
#define IDC_USE_ROMBROWSER              1133
#define IDC_USING                       1134
#define IDC_AVALIABLE                   1135
#define IDC_REMOVE                      1137
#define IDC_RECURSION                   1138
#define IDC_V64                         1141
#define IDC_LOAD_FULLSCREEN             1142
#define IDC_Z64                         1142
#define IDC_ROMSEL_TEXT5                1143
#define IDC_REMEMBER_CHEAT              1143
#define IDC_N64                         1143
#define IDC_ROMSEL_TEXT6                1144
#define IDC_SCREEN_SAVER                1144
#define IDC_ROM                         1144
#define IDC_CHECK_RUNNING               1144
#define IDC_BASIC_MODE                  1145
#define IDC_JAP                         1145
#define IDC_UNIQUE_SAVE_DIR             1145
#define IDC_PAL                         1146
#define IDC_USA                         1147
#define IDC_SHELL_INT_TEXT              1149
#define IDC_RDB_HOME                    1150
#define IDC_COUNTFACT                   1151
#define IDC_CHT_HOME                    1151
#define IDC_RDX_HOME                    1152
#define IDC_MEMORY_SIZE_TEXT            1153
#define IDC_SAVE_TYPE_TEXT              1154
#define IDC_LAN                         1154
#define IDC_LAN_AUTHOR                  1155
#define IDC_LAN_VERSION                 1156
#define IDC_SYNC_AUDIO                  1156
#define IDC_USE_TLB                     1157
#define IDC_LAN_DATE                    1157
#define IDC_RDB                         1158
#define IDC_RDB_AUTHOR                  1159
#define IDC_RDB_VERSION                 1160
#define IDC_RDB_DATE                    1161
#define IDC_CHT                         1162
#define IDC_CHT_AUTHOR                  1163
#define IDC_CHT_VERSION                 1164
#define IDC_CHT_DATE                    1165
#define IDC_RDX                         1166
#define IDC_RDX_AUTHOR                  1167
#define IDC_RDX_VERSION                 1168
#define IDC_RDX_DATE                    1169
#define IDC_NEWCHEAT                    1172
#define IDC_INFO_LOCATION               1178
#define IDC_CHEAT_CODES                 1178
#define IDC_STATE                       1179
#define IDC_CHEATSFRAME                 1188
#define IDC_ADDCHEATSFRAME              1189
#define IDC_CHEAT_OPTIONS               1190
#define IDC_ROM_NAME                    1191
#define IDC_LABEL_OPTIONS               1191
#define IDC_FILE_NAME                   1192
#define IDC_LABEL_OPTIONS_FORMAT        1192
#define IDC_LOCATION                    1193
#define IDC_ROM_SIZE                    1194
#define IDC_CART_ID                     1195
#define IDC_MANUFACTURER                1196
#define IDC_COUNTRY                     1197
#define IDC_CRC1                        1198
#define IDC_CRC2                        1199
#define IDC_CIC_CHIP                    1200
#define IDC_ROM_MD5                     1201
#define IDC_NOTESFRAME                  1201
#define IDC_NOTE                        1205
#define IDC_DIGITAL_TEXT                1206
#define IDC_VALUE_TEXT                  1207
#define IDC_NOTES_TEXT                  1208
#define IDC_LANG_SEL                    1219
#define IDC_IPL_DIR                     1220
#define IDC_SELECT_IPL_DIR              1221
#define IDC_IPLDIR_TXT                  1222
#define ID_POPUP_SHOWINMEMORYVIEWER     40005
#define ID_POPUPMENU_PLAYGAMEWITHDISK   40008
#define ID_POPUPMENU_ROMDIRECTORY       40137
#define ID_POPUPMENU_REFRESHROMLIST     40138
#define ID_POPUPMENU_PLAYGAME           40152
#define ID_POPUPMENU_EDITSETTINGS       40153
#define ID_POPUPMENU_EDITCHEATS         40154
#define ID_POPUPMENU_ROMINFORMATION     40155
#define ID_POPUP_ADDNEWCHEAT            40161
#define ID_POPUP_EDIT                   40162
#define ID_POPUP_DELETE                 40163

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         40009
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
