@echo off

SET current_dir=%cd%
cd /d %~dp0..\..\
SET base_dir=%cd%
cd /d %current_dir%

mkdir "%base_dir%\Bin\Package"
mkdir "%base_dir%\Bin\Package\Config"
mkdir "%base_dir%\Bin\Package\Lang"
mkdir "%base_dir%\Bin\Package\Plugin"
mkdir "%base_dir%\Bin\Package\Plugin\Audio"
mkdir "%base_dir%\Bin\Package\Plugin\GFX"
mkdir "%base_dir%\Bin\Package\Plugin\Input"
mkdir "%base_dir%\Bin\Package\Plugin\RSP"

copy "%base_dir%\Bin\Release\Project64.exe" "%base_dir%\Bin\Package"
copy "%base_dir%\Docs\Release Docs\PJgameFAQ.chm" "%base_dir%\Bin\Package"
copy "%base_dir%\Docs\Release Docs\Project64.chm" "%base_dir%\Bin\Package"
copy "%base_dir%\Config\Project64.cht" "%base_dir%\Bin\Package\Config"
copy "%base_dir%\Config\Project64.rdb" "%base_dir%\Bin\Package\Config"
copy "%base_dir%\Config\Project64.rdx" "%base_dir%\Bin\Package\Config"
copy "%base_dir%\Config\Glide64.rdb" "%base_dir%\Bin\Package\Config"
copy "%base_dir%\Lang\Brazilian Portuguese.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Bulgarian.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Chinese (Simplified).pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Chinese (Taiwan).pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Chinese (Traditional).pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\ChineseB5.pj.lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\ChineseGB.pj.lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Czech.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Danish.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Dutch.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\English.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\English_alternative.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Finnish.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\French.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\German.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\German_int.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\German_localised.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Greek.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Hungarian.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Italian.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Italian_alternative.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Japanese.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Lithuanian.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Norwegian.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Polish.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Russian.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Spanish (South America).pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Spanish (Spain).pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Spanish.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Swedish.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\T-Chinese.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Lang\Ukrainian.pj.Lang" "%base_dir%\Bin\Package\Lang"
copy "%base_dir%\Plugin\Audio\Jabo_Dsound.dll" "%base_dir%\Bin\Package\Plugin\Audio"
copy "%base_dir%\Plugin\GFX\Jabo_Direct3D8.dll" "%base_dir%\Bin\Package\Plugin\GFX"
copy "%base_dir%\Plugin\GFX\PJ64Glide64.dll" "%base_dir%\Bin\Package\Plugin\GFX"
copy "%base_dir%\Plugin\Input\PJ64_NRage.dll" "%base_dir%\Bin\Package\Plugin\Input"
copy "%base_dir%\Plugin\RSP\RSP 1.7.dll" "%base_dir%\Bin\Package\Plugin\RSP"
