#pragma once

enum RSPPIPELINE_STAGE
{
    RSPPIPELINE_NORMAL,
    RSPPIPELINE_DO_DELAY_SLOT,
    RSPPIPELINE_DO_DELAY_SLOT_EXIT,
    RSPPIPELINE_DO_DELAY_SLOT_TASK_EXIT,
    RSPPIPELINE_DELAY_SLOT,
    RSPPIPELINE_DELAY_SLOT_DONE,
    RSPPIPELINE_DELAY_SLOT_EXIT,
    RSPPIPELINE_DELAY_SLOT_EXIT_DONE,
    RSPPIPELINE_DELAY_SLOT_TASK_EXIT,
    RSPPIPELINE_DELAY_SLOT_TASK_EXIT_DONE,
    RSPPIPELINE_JUMP,
    RSPPIPELINE_SINGLE_STEP,
    RSPPIPELINE_SINGLE_STEP_DONE,
    RSPPIPELINE_FINISH_BLOCK,
    RSPPIPELINE_FINISH_SUB_BLOCK,
    RSPPIPELINE_FINISH_TASK_SUB_BLOCK,
};